### PR TITLE
Added CEO Compensation endpoint

### PR DESCRIPTION
**Pull request by juancarlosqr**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature: Adds the CEO compensation endpoint

- **What is the current behavior?** (You can also link to an open issue here)

The CEO compensation is not available 

- **What is the new behavior (if this is a feature change)?**

The CEO compensation is available

- **Other information**:

Hi, I'm sending this as part of the Hacktoberfest 2020. Thanks!

### CODE REVIEW

**Comment by chatman-media** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/endpoints/ceo-compensation/CeoCompensation.test.ts  1
- src/endpoints/ceo-compensation/CeoCompensation.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/farvistadw/iex-cloud/pullRequest?prid=6384379&bid=20706350)

**Comment by juancarlosqr** [comment]
Hi @zishe, in order for this PR to be accepted for the Hacktoberfest you would have to add the right label:

> An individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

If you can do that, I would highly appreciate it! 🤞🏼

**Comment by chatman-media** [comment]
Hi, @juancarlosqr , thanks for PR. I've added label, check is everything okay, I never done this before.

**Comment by juancarlosqr** [comment]
@zishe all good, it worked! Thanks

**Pull request merged**
